exports.authValidation = require('./auth')
exports.accountValidation = require('./account')
exports.topicValidation = require('./topic')
exports.storyValidation = require('./story')
exports.commentValidation = require('./comment')
exports.notificationsValidation = require('./notification')
