exports.authController = require('./auth')
exports.accountController = require('./account')
exports.topicController = require('./topic')
exports.storyController = require('./story')
exports.rootController = require('./root')
exports.faqCategoryController = require('./faqcategory')
exports.faqController = require('./faq')
